server:
  port: 9090

spring:
  security:
    user:
      name: angelo
      password: 123456
  datasource:
    url: jdbc:hsqldb:file:C:/localBD/EspInteg
    username: sa
    password: 
    driverClassName: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        SQL: DEBUG
security:
  keyEncript: FBlBRsMjc0w/BggFv+bcKiSbqOAM/HVT5eMc2sJpgTsEDkGrPlrmeKvMLb7Amu8T
  timeToken: 600000

